# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBMConnect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIBMConnect

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'IQKeyboardManagerSwift', '5.0.0'
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Kingfisher', '4.0'

  target 'NIBMConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIBMConnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
